project_rater/urls.py
from django.contrib import admin
from django.urls import path, include
from rest_framework.authtoken.views import obtain_auth_token

urlpatterns = [
    path('', include('projects.urls')),
    path('admin/', admin.site.urls),
    path('tinymce', include('tinymce.urls')),
    path('accounts/', include('django_registration.backends.one_step.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('api-token-auth/', obtain_auth_token),
]

projects/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from . import views

app_name = 'projects'

urlpatterns = [
    path('', views.index, name='index'),
    path('profile/<int:profile_id>', views.user_profile, name='profile'),
    path('add_project', views.add_project, name='add_project'),
    path('search', views.search_by_project_title, name='search_results'),
    path('<int:pk>', views.DetailView.as_view(), name='detail'),
    path('rating/<project>', views.rate_project, name='rate_project'),
    path('new_profile/', views.new_profile, name='new_profile'),
    path('api/projects', views.ProjectList.as_view()),
    path('api/project/project-id/<pk>', views.PostDescription.as_view()),
    path('api/users', views.UsersList.as_view()),
    path('ajax/rating', views.rating, name="rating"),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

projects/models.py
from django.db import models
from django.contrib.auth.models import User
from tinymce.models import HTMLField

# Create your models here.
class Profile(models.Model):
    """
    class facilitates the creation of profile objects
    """
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name='profile')
    bio = models.CharField(max_length=70)
    location = models.CharField(max_length=60)
    profile_pic = models.ImageField(upload_to='profiles/', default='episode-1-wallpaper-16x9.jpg')
    created_at = models.DateTimeField(auto_now_add=True)
    def save_profile(self):
        """
        method saves added profile
        """
        self.save()
    
    def update_profile(self, using=None, fields=None, **kwargs):
        """
        class method updates profile properties
        """
        if fields is not None:
            fields = set(fields)
            deferred_fields = self.get_deferred_fields()
            if fields.intersection(deferred_fields):
                fields = fields.union(deferred_fields)
        super().refresh_from_db(using, fields, **kwargs)

    def delete_profile(self):
        """
        method deletes saved profile
        """
        self.delete()

class Tags(models.Model):
    """
    class facilitates the creation of language objects
    """
    name = models.CharField(max_length=60)

    def __str__(self):
        return f'{self.name}'

    def save_tags(self):
        """
        method saves added tag
        """
        self.save()
    
    def update_tags(self, using=None, fields=None, **kwargs):
        """
        method updates saves tag
        """
        if fields is not None:
            fields = set(fields)
            deferred_fields = self.get_deferred_fields()
            if fields.intersection(deferred_fields):
                fields = fields.union(deferred_fields)
        super().refresh_from_db(using, fields, **kwargs)

    def delete_tags(self):
        """
        method deletes saved tag
        """
        self.delete()

class Project(models.Model):
    """
    class facilitates the creation of project objects
    """
    title = models.CharField(max_length=60)
    creator = models.ForeignKey(Profile, on_delete=models.CASCADE)
    project_image = models.ImageField(upload_to='projects/')
    description = HTMLField()
    live_link = models.CharField(max_length=200)
    tags = models.ManyToManyField(Tags)
    pub_date = models.DateTimeField(auto_now_add=True, null=True)

    def __str__(self):
        return self.title

    def save_project(self):
        """
        method saves added project object
        """
        self.save()
    
    def update_project(self, using=None, fields=None, **kwargs):
        """
        method updates saved project object
        """
        if fields is not None:
            fields = set(fields)
            deferred_fields = self.get_deferred_fields()
            if fields.intersection(deferred_fields):
                fields = fields.union(deferred_fields)
        super().refresh_from_db(using, fields, **kwargs)
    
    def delete_project(self):
        """
        method deletes saved project object
        """
        self.delete()
    
    @classmethod
    def search_by_title(cls, search_term):
        """
        method returns profiles that match the provided search term
        """
        projects = cls.objects.filter(title__icontains=search_term)
        return projects

class Votes(models.Model):
    """
    class facilitates the creation of ratng objects
    """
    design = models.IntegerField(choices=[(i, i) for i in range(1, 11)])
    usability = models.IntegerField(choices=[(i, i) for i in range(1, 11)])
    content = models.IntegerField(choices=[(i, i) for i in range(1, 11)])
    project = models.ForeignKey(Project, on_delete=models.CASCADE, null=True)
    rater = models.ForeignKey(User, on_delete=models.CASCADE)
    def __str__(self):
        return f'{self.rater.username}'

projects/forms.py
from django import forms
from .models import Profile, Project, Votes

class RegistrationForm(forms.Form):
    """
    class facilitates the creation of registration form objects
    """
    username = forms.CharField(max_length=30)
    first_name = forms.CharField(max_length=40)
    last_name = forms.CharField(max_length=40)
    email = forms.EmailField()
    password = forms.CharField()
    confirm_password = forms.CharField()
    bio = forms.CharField(max_length=70)

    def save(self):
        """
        method saves created user
        """
        new_user = Profile.objects.create(
            username=self.cleaned_data['username'],
            first_name=self.cleaned_data['first_name'],
            last_name=self.cleaned_data['last_name'],
            email=self.cleaned_data['email'],
            password=self.cleaned_data['password'],
            bio=self.cleaned_data['bio'],
        )
        return new_user

class ProjectsForm(forms.ModelForm):
    """
    class facilitates the generation of a form to facilitate the addition of new projects
    """
    class Meta:
        model = Project
        exclude = ['creator', 'design', 'usability', 'content', 'pub_date'] 

class VotesForm(forms.ModelForm):
    """
    class facilitates the generation of vote form objects
    """
    class Meta:
        model = Votes
        fields = ['design', 'usability', 'content']

class ProfileForm(forms.ModelForm):
    """
    class facilitates the creation of profile form objects
    """
    class Meta:
        model = Profile
        exclude = ['user']
         

projects/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Profile, Tags, Project, Votes
from django.views import generic
from .forms import RegistrationForm, ProjectsForm, VotesForm, ProfileForm
from django.contrib.auth import authenticate, login
from django.contrib import messages
from django.template import RequestContext
from django.contrib.auth.decorators import login_required
from django.http import Http404, HttpResponseRedirect, JsonResponse
from django.core.exceptions import ObjectDoesNotExist
from django.urls import reverse
from rest_framework.response import Response
from rest_framework.views import APIView
from .serializer import ProjectSerializer, PostSerializer, UserSerializer, ProfileSerializer
from rest_framework import status
from .permissions import IsAuthenticatedOrReadOnly

# Create your views here.
@login_required(login_url='/accounts/login')
def index(request):
    """
    view function renders the landing page
    """
    projects = Project.objects.all()
    return render(request, 'projects/index.html', {'projects':projects})

@login_required(login_url='/accounts/login')
def user_profile(request, profile_id):
    """
    view function renders user's profile page
    """
    try:
        profile = Profile.objects.filter(id=profile_id)
    except ObjectDoesNotExist:
        raise Http404
    projects = Project.objects.filter(id=profile_id)
    return render(request, 'profile/profile.html', {'profile':profile, 'projects':projects})

@login_required(login_url='/accounts/login')
def add_project(request):
    """
    view function renders the template that displays project form
    """
    profiles = Profile.objects.all()
    current_user = request.user.profile
    for profile in profiles:
        if profile.user.id == request.user.id:
            if request.method == 'POST':
                form = ProjectsForm(request.POST, request.FILES)
                if form.is_valid():
                    project = form.save(commit=False)
                    project.creator = current_user
                    project.save()
                return redirect('projects:index')
            else:
                form = ProjectsForm()
    return render(request, 'projects/upload_project.html', {'form':form, 'profiles':profiles})

@login_required(login_url='/accounts/login')
def search_by_project_title(request):
    """
    view function renders template that displays search results
    """
    if 'project' in request.GET and request.GET['project']:
       search_term = request.GET.get('project')
       projects = Project.search_by_title(search_term)
       message = f'{search_term}'
       return render(request, 'projects/results.html', {'message':message, 'projects':projects})
    else:
        message = 'Please enter a search term'
        return render(request, 'projects/results.html', {'message':message}) 

class DetailView(generic.DetailView):
    """
    class renders view that displays project-specific details
    """
    model = Project
    template_name = 'projects/detail.html'

    def get_queryset(self):
        return Project.objects.all()

@login_required(login_url='/accounts/login')
def rate_project(request, project):
    """
    view function renders rating and results views
    """
    project = Project.objects.filter(title=project).first()
    current_user = request.user
    votes = Votes.objects.filter(project=project)
    if request.method == 'POST':
        form = VotesForm(request.POST)
        votes = form.save(commit=False)
        votes.rater = request.user
        votes.project = project
        votes.save()
        project_ratings = Votes.objects.filter(project=project)
        design_mean_rating = []
        for d_rating in project_ratings:
            design_mean_rating.append(d_rating.design)
            design_average = sum(design_mean_rating)/len(design_mean_rating)
        usability_mean_rating = []
        for u_rating in project_ratings:
            usability_mean_rating.append(u_rating.usability)
            usability_average = sum(usability_mean_rating)/len(usability_mean_rating)
        content_mean_rating = []
        for c_rating in project_ratings:
            content_mean_rating.append(c_rating.content)
            content_average = sum(content_mean_rating)/len(content_mean_rating)
        votes.save()
        return HttpResponseRedirect(request.path_info)
    else:
        form = VotesForm()
        project_ratings = Votes.objects.filter(project=project)
    return render(request, 'projects/rate.html', {'form':form, 'project':project, 'project_ratings':project_ratings})

def rating(request):
    """
    ajax view function
    """
    design = request.POST.get('design')
    usability = request.POST.get('usability')
    content = request.POST.get('content')
    votes = Votes(design=design, usability=usability, content=content)
    votes.save()
    data = {'success': 'Thank you for voting'}
    return JsonResponse(data)

@login_required(login_url='/accounts/login/')
def new_profile(request):
    """
    view function renders form for creating new profile
    """
    current_user = request.user
    if request.method == 'POST':
        form = ProfileForm(request.POST, request.FILES)
        if form.is_valid():
            profile = form.save(commit=False)
            profile.user = current_user
            profile.save()
        return redirect('projects:index')
    else:
        form = ProfileForm()
    return render(request, 'projects/new_profile.html', {"form":form})

class ProjectList(APIView):
    """
    class view inherits from APIView
    """
    permission_classes = (IsAuthenticatedOrReadOnly,)
    def get(self, request, format=None):
        all_projects = Project.objects.all()
        serializers = ProjectSerializer(all_projects, many=True)
        return Response(serializers.data)
    
    def post(self, request, format=None):
        serializers = ProjectSerializer(data=request.data)
        if serializers.is_valid():
            serializers.save()
            return Response(serializers.data, status=status.HTTP_201_CREATED)
        return Response(serializers.errors, status=status.HTTP_400_BAD_REQUEST)
    

class PostDescription(APIView):
    """
    class view inherits from APIView
    """
    permission_classes = (IsAuthenticatedOrReadOnly,)
    def get_project(self, pk):
        try:
            return Project.objects.get(pk=pk)
        except ObjectDoesNotExist:
            return Http404
    def get(self, request, pk, format=None):
        project = self.get_project(pk)
        serializers = PostSerializer(project)
        return Response(serializers.data)
    def put(self, request, pk, format=None):
        project = self.get_project(pk)
        serializers = PostSerializer(project, request.data)
        if serializers.is_valid():
            serializers.save()
            return Response(serializers.data)
        else:
            return Response(serializers.errors, status=status.HTTP_400_BAD_REQUEST)
    def delete(self, request, pk, format=None):
        project = self.get_project(pk)
        project.delete()
        return Response(status=status.HTTP_204_NO_CONTENT)

class UsersList(APIView):
    """
    class view inherits from APIView
    """
    permission_classes = (IsAuthenticatedOrReadOnly,)
    def get(self, request, format=None):
        all_users = Profile.objects.all()
        serializers = ProfileSerializer(all_users, many=True)
        return Response(serializers.data)
    def post(self, request, format=None):
        serializers = ProfileSerializer(data=request.data)
        if serializers.is_valid():
            serializers.save()
            return Response(serializers.data, status=status.HTTP_201_CREATED)
        return Response(serializers.errors, status=status.HTTP_400_BAD_REQUEST)

projects/templates/projects/detail.html
{% load bootstrap4 %}
{% load static %}
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width initial-scale=1">
        <title>Profile</title>
        {% block styles %}
            {% bootstrap_css %}
            <link rel="stylesheet" type="text/css" href="{% static 'projects.css' %}">
        {% endblock %}
        <link rel="shortcut icon" type="image/png" href="{% static 'favicon.ico' %}">
    </head>
    <body>
        {% include 'navbar.html' %}
        <div class="container">
            <div class="row">
                <div class="col-md-2"></div>
                <div class="col-md-8">
                    <div class="card mb-3" style="width: 40rem;">
                        <img class="card-img-top img-responsive" src="{{project.project_image.url}}">
                        <div class="card-body">
                            <div class="card-title"><strong>{{project.title}}</strong> by <i>{{project.creator.user.username}}</i> <span style="float: right;">{{project.pub_date|timesince}}</span></div>
                            
                            {% autoescape on %}
                            <p><i>{{project.description|safe}}</i></p>
                            {% endautoescape %}
                            <a href="{{project.live_link}}" target="_blank"><i class="fa fa-external-link"></i></a>
                        </div>
                    </div>
                </div>
                <div class="col-md-2"></div>
            </div>
            
        </div>
        {% block scripts %}
            <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
            {% bootstrap_javascript %}
        {% endblock %}
    </body>
</html>

projects/templates/projects/index.html
{% load bootstrap4 %}
{% load static %}
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width initial-scale=1">
        <title>Project Rater</title>
        {% block styles %}
            {% bootstrap_css %}
            <link rel="stylesheet" type="text/css" href="{% static 'index.css' %}">
        {% endblock %}
        <link rel="shortcut icon" type="image/png" href="{% static 'favicon.ico' %}">
    </head>
    <body>
        {% include 'navbar.html' %}
        <div class="jumbotron">
            <h1 style="margin-top: 60px;">Project Rater</h1>
            <h3>Review and Ask Others To Review Your Site</h3>
        </div>
        <div class="container-fluid">
            <h2 class="text-center">Projects to View and Review</h2>
            <hr>
            <div class="row">
                {% for project in projects %}
                    <div class="card mb-3" style="width: 20rem; margin-left: 35px;">
                        <img src="{{project.project_image.url}}" class="card-img-top">
                        <div class="card-body">
                            <div class="card-title">{{project.title}}</div>
                            <a style="font-size: small;" href="{% url 'projects:rate_project' project.title %}">View Project Details</a>
                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>
    </body>
</html>

projects/templates/projects/new_profile.html
{% load bootstrap4 %}
{% load static %}
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>New Profile</title>
        
        {{form.media}}
        
        {% block styles %}
            {% bootstrap_css %}
            <link rel="stylesheet" type="text/css" href="{% static 'profiles/css/index.css' %}">
        {% endblock %}
        <link href="https://fonts.googleapis.com/css2?family=Lobster&display=swap" rel="stylesheet">
    </head>
    <body>
        <div class="container" style="margin-top: 50px;">
            <h1 class="text-center">Create Your Profile</h1>
            <div class="row">
                <div class="col-md-4 col-sm-6"></div>
                <div class="col-md-4 col-sm-6">
                    <form action="{% url 'projects:new_profile'%}" method='post' enctype="multipart/form-data">
                        {% csrf_token %}
                        {% bootstrap_form form %}
                        <input style="margin-left:110px;" type="submit" class="btn btn-primary btn-sm" value="Post">
                    </form>
                </div>
                <div class="col-md-4 col-sm-6"></div>
            </div>
        </div>
        {% block scripts %}
            <script src="https://code.jquery.com/jquery-3.5.1.min.js" integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous"></script>
            {% bootstrap_javascript %}
        {% endblock %}
    </body>
</html>

projects/templates/projects/rate.html
{% load bootstrap4 %}
{% load static %}

<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width initial-scale=1">
        <title>Project Rater</title>
        {% block styles %}
            {% bootstrap_css %}
            <link rel="stylesheet" type="text/css" href="{% static 'projects.css' %}">
        {% endblock %}
        <link rel="shortcut icon" type="image/png" href="{% static 'favicon.ico' %}">
    </head>
    <body>
        {% include 'navbar.html' %}
        <h1 class="text-center" style="margin-top: 50px;">{{project.title}}</h1>
        <div class="container-fluid" style="margin-top:70px">
            
            <div class="row">
                <div class="col-md-4">
                    <h4>Rate Project</h4>
                    <form action="" method='post'>
                        {% csrf_token %}
                        {% bootstrap_form form %}
                        <input type="submit" value="Post">
                    </form>
                </div>
                <div class="col-md-8">
                    <div class="card mb-3" style="width: 40rem;">
                        <img class="card-img-top img-responsive" src="{{project.project_image.url}}">
                        <div class="card-body">
                            <div class="card-title"><strong>{{project.title}}</strong> by <i>{{project.creator.user.username}}</i> <span style="float: right;">{{project.pub_date|timesince}}</span></div>
                            
                            {% autoescape on %}
                            <p><i>{{project.description|safe}}</i></p>
                            {% endautoescape %}
                            <a href="{{project.live_link}}" target="_blank"><i class="fa fa-external-link"></i></a>
                        </div>
                    </div>
                </div>
            </div>
            
        </div>
        <div class="container-fluid" style="margin-top:50px">
            <div class="row">
                <div class="col-md-12">
                    <h3 class="text-center">Project's Ratings</h3>
                    <hr>
                    <table class="table table-dark table-hover">
                       <thead>
                           <tr>
                               <th scope="col">#</th>
                               <th scope="col">User</th>
                               <th scope="col">Design</th>
                               <th scope="col">Usability</th>
                               <th scope="col">Content</th>
                           </tr>
                       </thead>
                       <tbody>
                           <tr>
                               <td>{{design_average}}</td>
                               <td>{{usability_average}}</td>
                               <td>{{content_average}}</td>
                           </tr>
                           {% if project_ratings %}
                           {% for vote in project_ratings %}
                           <tr class="rate{{vote.user.id}}">
                               <th scope="row">{{forloop.counter}}</th>
                               <td>{{vote.user.rater}}</td>
                               <td>{{vote.design}}</td>
                               <td>{{vote.usability}}</td>
                               <td>{{vote.content}}</td>
                           </tr>
                           {% endfor %}
                           {% endif %}
                       </tbody>
                    </table>
                </div>
                
            </div>
        </div>
        <div class="container"></div>
        {% block scripts %}
            <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
            <script type="text/javascript" src="{% static 'js/projects.js' %}"></script>
            {% bootstrap_javascript %}
        {% endblock %}
    </body>
</html>

projects/templates/projects/results.html
{% load bootstrap4 %}
{% load static %}
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width initial-scale=1">
        <title>Profile</title>
        {% block styles %}
            {% bootstrap_css %}
            <link rel="stylesheet" type="text/css" href="{% static 'index.css' %}">
        {% endblock %}
        <link rel="shortcut icon" type="image/png" href="{% static 'favicon.ico' %}">
    </head>
    <body>
        {% include 'navbar.html' %}
        <div class="container" style="margin-top: 50px; font-style: italic;">
            <div class="row">
                {% if projects %}
                    <h2 style="margin-left: 250px;">Found {{ projects|length }} result of searched term {{message}}</h2>
                {% else %}
                    <h2 style="margin-left: 250px;"> Found 0 projects for the search term {{message}}</h2>
                {% endif %}
            </div>
            <div class="row" style="margin-top: 30px;">
                {% for project in projects %}
                <div class="card mb-3" style="width: 20rem; margin-left: 10px;">
                    <img src="{{project.project_image.url}}" class="card-img-top">
                    <div class="card-body">
                        <div class="card-title">{{project.title}}</div>
                        <a style="font-size: small;" href="{% url 'projects:rate_project' project.title %}">View Project Details</a>
                    </div>
                </div>
            {% endfor %}
            </div>
            
        </div>
    </body>
</html>

projects/templates/projects/upload_project.html
{% load bootstrap4 %}
{% load static %}
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>New Project</title>
        
        {{form.media}}
        
        {% block styles %}
            {% bootstrap_css %}
            <link rel="stylesheet" type="text/css" href="{% static 'index.css' %}">
        {% endblock %}
        <link rel="shortcut icon" type="image/png" href="{% static 'favicon.ico' %}">
        <link href="https://fonts.googleapis.com/css2?family=Tenali+Ramakrishna&display=swap" rel="stylesheet">
        <script src="https://kit.fontawesome.com/79cafd0f3e.js" crossorigin="anonymous"></script>
    </head>
    <body>
        <div class="container" style="margin-top: 50px;">
            <h1 class="text-center">Add Project</h1>
            <div class="row">
                <div class="col-md-2 col-sm-6"></div>
                <div class="col-md-8 col-sm-6">
                    <form action="{% url 'projects:add_project'%}" method='post' enctype="multipart/form-data">
                        {% csrf_token %}
                        {% bootstrap_form form %}
                        <input style="margin-left:110px;" type="submit" class="btn btn-primary btn-md text-center" value="Post">
                    </form>
                </div>
                <div class="col-md-2 col-sm-6"></div>
            </div>
        </div>
        {% block scripts %}
            <script src="https://code.jquery.com/jquery-3.5.1.min.js" integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous"></script>
            {% bootstrap_javascript %}
        {% endblock %}
    </body>
</html>